name: use secrets
on: 
    push:
        branches:
            - main
run-name: creds
jobs:
    test:
        environment: testing
        runs-on: ubuntu-latest
        steps:
            - name: show value
              run: echo "hello there"
            - name: get secrets
              run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}